name: Deploy to Chrome Webstore

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip extension
        run: zip -r extension.zip . -x ".git/*"

      - name: Upload & Publish to Chrome Web Store
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          extension-id: ${{ secrets.APP_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          zip-path: ./extension.zip
